#!/bash/sh

if ! pacman -Qs vim > /dev/null ; then
	sudo pacman -Sy vim
fi

DIR=~/

cp -r vim-classic/. $DIR

[ -f $DIR.vim ] && rm -rf $DIR.vim

mkdir -p $DIR.vim $DIR.vim/autoload $DIR.vim/backup $DIR.vim/colors $DIR.vim/plugged

curl -fLo $DIR.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo 'vim configuration installed !!'
