#!/bash/sh

if ! pacman -Qs vim > /dev/null ; then
	sudo pacman -Sy vim
fi

DIR=~/
VIMDIR=$DIR.vim

[ -f $VIMDIR ] && rm -rf $VIMDIR

mkdir -p $VIMDIR $VIMDIR/autoload $VIMDIR/backup $VIMDIR/colors $VIMDIR/plugged

cp -r vim-classic/vimrc $DIR.vimrc

for file in sources/*
do
	cp -r vim-classic/$file $VIMDIR
done

curl -fLo $VIMDIR/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo 'vim installed !!'
