#!/bash/sh

sudo pacman -Sy ripgrep

git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim

DIR=~/.config/nvim
[[ -d "$DIR" ]] && rm -rf "$DIR"

mkdir $DIR

rsync -av --exclude=".*" lua/ $DIRi
rsync -av --exclude=".*" init.lua
