source ~/.vim/scripts.vim
source ~/.vim/autocommands.vim
source ~/.vim/plugins.vim
source ~/.vim/mappings.vim

" Cursor for normal

let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

" Setups

syntax on

set number
set hlsearch
set incsearch
set hidden

colorscheme gruvbox8
set bg=dark

set wildmenu
set wildmode=list:longest
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

