let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

syntax on

set number
set hlsearch
set incsearch

set wildmenu
set wildmode=list:longest
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

call plug#begin('~/.vim/plugged')

  	Plug 'preservim/nerdtree'

  	Plug 'tpope/vim-commentary'
  
  	Plug 'maxboisvert/vim-simple-complete'
  
  	Plug 'rust-lang/rust.vim'

	Plug 'neoclide/coc.nvim', {'branch': 'release'}

	Plug 'dense-analysis/ale'

call plug#end()


let mapleader = " "
nnoremap <leader>f :NERDTreeFocus<CR>
nnoremap <leader>e :NERDTreeToggle<CR>
